#! /bin/bash

PACKAGE="github.com/maansthoernvik/locksmith/pkg/version"
# VERSION
# COMMIT
BUILT="$(date)"

echo "Building $1..."
echo "Version: $VERSION"
echo "Commit: $COMMIT"
echo "Built: $BUILT"

LDFLAGS=(
  "-X '${PACKAGE}.Version=${VERSION}'"
  "-X '${PACKAGE}.Commit=${COMMIT}'"
  "-X '${PACKAGE}.Built=${BUILT}'"
)

echo "Building with LDFLAGS=${LDFLAGS[*]}"

# set any build flags such as CGO_ENABLED=0 GOOS=linux separately from this script.
go build -ldflags="${LDFLAGS[*]}" -o $1 $2
