#!/bin/bash

PACKAGE="github.com/maansthoernvik/locksmith"
VERSION="$(git describe --tags --always --abbrev=0)"
COMMIT="$(git rev-parse --short HEAD)"
BUILT="$(date)"

echo "Building Locksmith..."
echo "Version: $VERSION"
echo "Commit: $COMMIT"
echo "Built: $BUILT"

LDFLAGS=(
  "-X '${PACKAGE}/version.Version=${VERSION}'"
  "-X '${PACKAGE}/version.Commit=${COMMIT}'"
  "-X '${PACKAGE}/version.Built=${BUILT}'"
)

CGO_ENABLED=0 GOOS=linux go build -ldflags="${LDFLAGS[*]}" -o /locksmith
