#! /bin/bash

PACKAGE="github.com/maansthoernvik/locksmith"
# VERSION
# COMMIT
BUILT="$(date)"

echo "Building $1..."
echo "Version: $VERSION"
echo "Commit: $COMMIT"
echo "Built: $BUILT"

LDFLAGS=(
  "-X '${PACKAGE}/version.Version=${VERSION}'"
  "-X '${PACKAGE}/version.Commit=${COMMIT}'"
  "-X '${PACKAGE}/version.Built=${BUILT}'"
)

# set any build flags such as CGO_ENABLED=0 GOOS=linux separately from this script.
go build -ldflags="${LDFLAGS[*]}" -o $1 $2
